Eneo.Site/Controllers/PlacedItemController.cs
using Eneo.Helpers;
using Eneo.Model;
using Eneo.Model.Models.ViewModels;
using Eneo.Model.Repository;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Collections.Generic;
using CsQuery;
using System.Text.RegularExpressions;
using System.Linq;
using System;
using System.IO;
using Eneo.Model.Models.Entities;
using System.Threading.Tasks;
using System.Diagnostics;
using System.Net;

namespace Eneo.Site.Controllers
{
    [Authorize]
    public class PlacedItemController : Controller
    {
        private EneoContext _eneoCtx;
        private PlacedItemsRepo _placedItemsRepo;
        private CollectedItem _collectedItem;
        private string _imagePath;

        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            string rootServerPath = Directory.GetParent(HttpContext.Server.MapPath("//")).Parent.FullName;
            _imagePath = Path.Combine(rootServerPath, @"Images\MapPlacedImages\");
            if (!Directory.Exists(_imagePath))
            {
                Directory.CreateDirectory(_imagePath);
            }


        }

        public PlacedItemController()
        {
            _eneoCtx = new EneoContext();
            _placedItemsRepo = new PlacedItemsRepo(_eneoCtx);
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public HttpResponseMessage GetMapItemImage(string id)
        {
            HttpResponseMessage result = ImageHelper.GetImage(id, _imagePath);
            return result;
        }

        public ActionResult PlacedMapItems_Read([DataSourceRequest] DataSourceRequest request, PlacedItemModel model)
        {
            var items = _placedItemsRepo.GetMapItems();
            return Json(items.ToDataSourceResult(request));
        }

        public ActionResult PlacedItemComments_Read([DataSourceRequest] DataSourceRequest request, PlacedItemCommentModel model, int placedItemID)
        {
            var items = _placedItemsRepo.GetComments(placedItemID);
            return Json(items.ToDataSourceResult(request));
        }

        public ActionResult PlacedItemComments_Delete([DataSourceRequest] DataSourceRequest request, PlacedItemCommentModel model)
        {
            _placedItemsRepo.DeletePlacedItemComment(model.CommentID);
            return Json(new[] { model }.ToDataSourceResult(request, ModelState));
        }

        [AllowAnonymous]
        public ActionResult Test()
        {
            string path1 = HttpContext.Server.MapPath("~//App_Data//");
            string path2 = HttpContext.Server.MapPath("//App_Data//");
            string path3 = HttpContext.Server.MapPath("//");
            string path4 = HttpContext.Server.MapPath("~");
            string path5 = HttpContext.Server.MapPath("");

            return Json(new Tuple<string, string, string, string, string, string>(path1, path2, path3, path4, path5, ""), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(int id)
        {
            var mapPlacedItem = _placedItemsRepo.GetMapItem(id);
            ViewBag.CollectionItemList = GetCollectionItemSelectList;
            return View(mapPlacedItem);
        }

        [HttpPost]
        public ActionResult Edit(PlacedItemModel item, HttpPostedFileBase file)
        {
            if (file != null)
            {
                SaveImage(item, file);
            }
            if (ModelState.IsValid)
            {
                item = _placedItemsRepo.UpdateMapItem(item);
            }
            ViewBag.CollectionItemList = GetCollectionItemSelectList;
            return View(item);
        }

        private void SaveImage(PlacedItemModel item, HttpPostedFileBase file)
        {
            file.SaveAs(_imagePath + file.FileName);
            string fileGuid = Guid.NewGuid().ToString();
            System.IO.File.Move(_imagePath + file.FileName, _imagePath + fileGuid);
            item.ImageUrl = fileGuid;
        }

        public ActionResult GetWikiUrl()
        {
            string wikiUrl = "http://pl.wikipedia.org/wiki/Zabytki_Poznania";
            WikiUrlModel wiki = new WikiUrlModel
            {
                Value = wikiUrl
            };
            return View(wiki);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LoadFromWiki(WikiUrlModel wikiUrl)
        {
            var list = GetWikiPlaces(wikiUrl.Value).ToList();
            return View(list);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LoadedFromWiki(IEnumerable<PlacedItemWiki> model)
        {
            var itemsToAdd = model.Where(u => u.Add == true);
            GetWikiImages(itemsToAdd);
            _placedItemsRepo.AddWikiPlaces(itemsToAdd);
            return RedirectToAction("Index");
        }

        private void GetWikiImages(IEnumerable<PlacedItemWiki> places)
        {
            Parallel.ForEach(places, place =>
                {
                    if (!string.IsNullOrEmpty(place.ImageUrl))
                    {
                        WebClient client = new WebClient();
                        client.DownloadFile(new Uri(place.ImageUrl), _imagePath + place.Name);
                        Guid imageGuid = Guid.NewGuid();
                        System.IO.File.Move(_imagePath + place.Name, _imagePath + imageGuid.ToString());
                        place.ImageUrl = imageGuid.ToString();
                    }
                });
        }



        public ActionResult Add()
        {
            ViewBag.CollectionItemList = GetCollectionItemSelectList;
            return View(new PlacedItemModel
            {
                Latitude = "52.406391",
                Longitude = "16.925341",
                AddedDate = DateTime.Now
            });
        }

        [HttpPost]
        public ActionResult Add(PlacedItemModel item, HttpPostedFileBase file)
        {
            if (file != null)
            {
                SaveImage(item, file);
            }
            if (ModelState.IsValid)
            {
                item = _placedItemsRepo.AddMapItem(item);
            }
            ViewBag.CollectionItemList = GetCollectionItemSelectList;
            return RedirectToAction("Edit", new { id = item.PlacedItemID });
        }

        public ActionResult PlacedMapItem_Delete([DataSourceRequest] DataSourceRequest request, PlacedItemModel model)
        {
            _placedItemsRepo.DeleteMapItem(model.PlacedItemID);
            return Json(new[] { model }.ToDataSourceResult(request, ModelState));
        }
        public ActionResult PlacedMapItems_LoadFromWiki([DataSourceRequest] DataSourceRequest request, PlacedItemWiki model)
        {
            List<PlacedItemWiki> list = GetWikiPlaces("http://pl.wikipedia.org/wiki/Zabytki_Poznania");
            return Json(list.ToDataSourceResult(request));
        }

        private static List<PlacedItemWiki> GetWikiPlaces(string wikiUrl)
        {
            List<PlacedItemWiki> list = new List<PlacedItemWiki>();
            Uri uri = new Uri(wikiUrl);
            string wikipedia = uri.GetLeftPart(UriPartial.Authority);
            string name = wikiUrl.Replace(wikipedia, string.Empty);


            var dom = CQ.CreateFromUrl(wikiUrl);
            CQ hrefs = dom.Select("a").RemoveAttr("title").RemoveAttr("class").RemoveAttr("accesskey");

            Regex regexHref = new Regex(@"<a href=""(.*)"">");
            Regex regexGeo = new Regex("[A-Z](.*)[0-9][0-9]°");

            List<string> allLinks = new List<string>();

            foreach (var href in hrefs)
            {
                var v = regexHref.Match(href.ToString());
                string s = v.Groups[1].ToString();
                if (s.Contains(".jpg") == false && s.Contains(".JPG") == false && s.Contains(".svg") == false && s.Contains("wikimedia") == false
                    && s.Contains("Wikipedia") == false && s.Contains("wikidata") == false && s.Contains("Pomoc") == false && s.Contains(name) == false
                    && s.Contains("mediawiki") == false && s.Contains("Specjalna") == false && s.Contains("Portal") == false && s.Contains("/wiki/") == true)
                    allLinks.Add(wikipedia + s);
            }

            foreach (var link in allLinks)
            {
                PlacedItemWiki item = new PlacedItemWiki();

                CQ domInternal = null;
                try
                {
                    domInternal = CQ.CreateFromUrl(link);
                }
                catch (Exception ex)
                {
                    Debug.WriteLine(ex.Message);
                }
                if (domInternal != null)
                {
                    CQ latitudes = domInternal.Select(".latitude").Text();
                    CQ longitudes = domInternal.Select(".longitude").Text();
                    CQ names = domInternal.Select("#firstHeading").Text();
                    CQ description = domInternal.Select("#mw-content-text").Select("p:first").Text();
                    CQ imageUrl = domInternal.Select("#mw-content-text img").Attr("src");

                    var vLatitude = regexGeo.Match(latitudes.ToString());
                    string sLatitude = vLatitude.Groups[1].ToString();
                    var vLongitude = regexGeo.Match(longitudes.ToString());
                    string sLongitude = vLongitude.Groups[1].ToString();

                    if (latitudes.ToString() != "")
                    {
                        item.Name = names.ToString().Replace("\n", string.Empty).Replace("\t", string.Empty);
                        item.Latitude = sLatitude.Replace(" ", string.Empty);
                        item.Longitude = sLongitude.Replace(" ", string.Empty);
                        item.ImageUrl = "http:"+imageUrl.Text();

Eneo.Site/Views/PlacedItem/Add.cshtml
@model Eneo.Model.Models.ViewModels.PlacedItemModel

@{
    ViewBag.Title = "AddMapItem";
}

<h2>AddPlacedMapItem</h2>

<script type="text/javascript" src="http://ecn.dev.virtualearth.net/mapcontrol/mapcontrol.ashx?v=7.0"></script>
<script type="text/javascript">
    var map = null;
    var latitude = @Model.Latitude;
    var longitude = @Model.Longitude;

    function getMap() {
        map = new Microsoft.Maps.Map(document.getElementById('MyMap'), {
            credentials: 'AgMMZ260fXQbBMIZQAvSThzwOPRjJ7w3PFVsCUvsihB6533NCvTWw3rTIus84Br2',
            showDashboard: false
        });
        addPushpinWithOptions();
    };

    function addPushpinWithOptions() {
        var offset = new Microsoft.Maps.Point(0, 5);
        var pushpinOptions = {
            //text: '1',
            visible: true,
            textOffset: offset,
            draggable:true
        };
        var pushpin = new Microsoft.Maps.Pushpin(
            new Microsoft.Maps.Location(latitude, longitude),
            pushpinOptions);
        var pushpindragend= Microsoft.Maps.Events.addHandler(pushpin, 'dragend', endDragDetails);
        map.setView({
            center: new Microsoft.Maps.Location(latitude,  longitude),
            zoom: 12
        });
        map.entities.push(pushpin);
    };

    endDragDetails = function (e)
    {
        var pinLocation = e.entity.getLocation();
        latitude = pinLocation.latitude.toFixed(4);
        longitude = pinLocation.longitude.toFixed(4);

        map.setView({
            center: new Microsoft.Maps.Location(latitude, longitude),
            zoom: 12
        });

        $('#Latitude').val(latitude);
        $('#Longitude').val(longitude);
    };

</script>

@using (Html.BeginForm("Add", "PlacedItem", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <body onload="getMap();">
    </body>

    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="row">
            <h4>MapPlacedItem</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="col-md-5">
                @Html.HiddenFor(model => model.PlacedItemID, new { htmlAttributes = new { @class = "form-control" } })
        

                @if (!string.IsNullOrEmpty(Model.ImageUrl))
                {
                    <div id="FormPhoto">
                        <img src="@Model.ImageUrl" />
                    </div>
                }

                <div class="form-group">
                    @Html.LabelFor(m => m.ImageUrl, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input class="form-control" type="file" id="ImagePath" title="Wczytaj obrazek" name="file" />
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.CollectionItemID, ViewBag.CollectionItemList as IEnumerable<SelectListItem>)
                    </div>
                </div>
                @Html.HiddenFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.HiddenFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })

                <div class="form-group">
                    @Html.LabelFor(model => model.AddedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AddedDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AddedDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-3">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
            <div class="col-md-7" id="MyMap"></div>

        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Eneo.Site/Views/PlacedItem/Edit.cshtml
@model Eneo.Model.Models.ViewModels.PlacedItemModel

@{
    ViewBag.Title = "EditMapItem";
    var newLatitude = @Model.Latitude;
    var newLongitude = @Model.Longitude;

}

<h2>EditMapItem</h2>


@*<script type="text/javascript" src="http://ecn.dev.virtualearth.net/mapcontrol/mapcontrol.ashx?v=7.0"></script>*@
@Scripts.Render("~/bundles/mapcontrol")

<script type="text/javascript">
    var map = null;
    var latitude = @Model.Latitude;
    var longitude = @Model.Longitude;

    function getMap() {
        map = new Microsoft.Maps.Map(document.getElementById('MyMap'), {
            credentials: 'AgMMZ260fXQbBMIZQAvSThzwOPRjJ7w3PFVsCUvsihB6533NCvTWw3rTIus84Br2',
            showDashboard: false
        });
        addPushpinWithOptions();
    };

    function addPushpinWithOptions() {
        var offset = new Microsoft.Maps.Point(0, 5);
        var pushpinOptions = {
            //text: '1',
            visible: true,
            textOffset: offset,
            draggable:true
        };
        var pushpin = new Microsoft.Maps.Pushpin(
            new Microsoft.Maps.Location(latitude, longitude),
            pushpinOptions);
        var pushpindragend= Microsoft.Maps.Events.addHandler(pushpin, 'dragend', endDragDetails);
        map.setView({
            center: new Microsoft.Maps.Location(latitude,  longitude),
            zoom: 12
        });
        map.entities.push(pushpin);
    };

    endDragDetails = function (e)
    {
        var pinLocation = e.entity.getLocation();
        latitude = pinLocation.latitude.toFixed(4);
        longitude = pinLocation.longitude.toFixed(4);

        map.setView({
            center: new Microsoft.Maps.Location(latitude, longitude),
            zoom: 12
        });

        $('#Latitude').val(latitude);
        $('#Longitude').val(longitude);
    };

</script>

@using (Html.BeginForm("Edit", "PlacedItem", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <body onload="getMap();">
    </body>

    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="row">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="col-md-5">
                @Html.HiddenFor(model => model.PlacedItemID, new { htmlAttributes = new { @class = "form-control" } })
                @if (!string.IsNullOrEmpty(Model.ImageUrl))
                {
                    <div class="form-group">
                        <label class="control-label col-md-2">Image</label>
                        <div class="col-md-10">
                            <div id="formphoto">
                                <img src="@Model.ImageUrl" />
                            </div>
                        </div>
                    </div>
                }


                <div class="form-group">
                    @Html.LabelFor(m => m.ImageUrl, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @*<input class="form-control" type="file" id="ImagePath" title="Wczytaj obrazek" name="file" />*@
                        <input class="form-control btn btn-primary" type="file" id="ImagePath" title="Wczytaj obrazek" name="file" />
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.CollectionItemID, ViewBag.CollectionItemList as IEnumerable<SelectListItem>, new { @class = "form-control" })
                    </div>
                </div>
                @Html.HiddenFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.HiddenFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })

                <div class="form-group">
                    @Html.LabelFor(model => model.AddedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AddedDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AddedDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-3">
                        <button type="submit" value="Save" class="btn btn-primary">
                            Save
                        </button>

                    </div>
                </div>
            </div>
            <div class="col-md-7" id="MyMap"></div>

        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@(Html.Kendo().Grid<Eneo.Model.Models.ViewModels.PlacedItemCommentModel>()
.Name("PlacedItemCommentGrid")
.Columns(cols =>
    {
        cols.Bound(p => p.CommentID).Hidden();
        cols.Bound(p => p.UserName);
        cols.Bound(p => p.Content);
        cols.Bound(p => p.AddedDate).Format("{0:dd/MM/yyyy HH:mm:ss}");
        cols.Command(cmd => { cmd.Destroy(); }).Width(105);
    })
    .DataSource(dataSource => dataSource
        .Ajax()
        .PageSize(20)
        .Model(model => model.Id(p => p.CommentID))
            .Read(read => read.Action("PlacedItemComments_Read", "PlacedItem", new { placedItemID = Model.PlacedItemID }))
                    .Destroy(delete => delete.Action("PlacedItemComments_Delete", "PlacedItem"))
        )
    .Editable(editable => editable.Mode(GridEditMode.PopUp))
    .Scrollable(scrollable => scrollable.Height(430))
    .Sortable()
    .Filterable()
    .Pageable(pageable => pageable
        .Refresh(true)
        .PageSizes(true)
        .ButtonCount(5))
)

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Eneo.Site/Views/PlacedItem/GetWikiUrl.cshtml
@model Eneo.Model.Models.ViewModels.WikiUrlModel

@{
    ViewBag.Title = "GetWikiUrl";
}

<h2>GetWikiUrl</h2>

@using (Html.BeginForm("LoadFromWiki","PlacedItem",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <p>Podaj url do strony z wiki zawierającej lokacje, np. <a href="@Model.Value">@Model.Value</a></p>
    @Html.EditorFor(m => Model.Value)
    
    <input type="submit" value="Pobierz"/>
}

Eneo.Site/Views/PlacedItem/LoadFromWiki.cshtml
@model List<Eneo.Model.Models.ViewModels.PlacedItemWiki>
@{
    ViewBag.Title = "Load";
}



<h2>Load from Wikipedia</h2>

@*<script type="text/javascript" src="http://ecn.dev.virtualearth.net/mapcontrol/mapcontrol.ashx?v=7.0"></script>*@

    @Scripts.Render("~/bundles/mapcontrol")

<script type="text/javascript">
    var map = null;
    var pinInfoBox;  //the pop up info box
    var infoboxLayer = new Microsoft.Maps.EntityCollection();
    var pinLayer = new Microsoft.Maps.EntityCollection();
    function getMap() {
        map = new Microsoft.Maps.Map(document.getElementById('myMap'), {
            credentials: 'AgMMZ260fXQbBMIZQAvSThzwOPRjJ7w3PFVsCUvsihB6533NCvTWw3rTIus84Br2',
            showDashboard: false
        });
        addPushpins();

        // Create the info box for the pushpin
        pinInfobox = new Microsoft.Maps.Infobox(new Microsoft.Maps.Location(0, 0), { visible: false });
        infoboxLayer.push(pinInfobox);

        var test = '@Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model).Replace("\\", string.Empty).Replace("\'",string.Empty))';
        var items = JSON.parse(test);

        var sumOfLat = 0;
        var sumOfLon = 0;
        var counter = 0;
        var itemLatString, itemLatFloat, itemLonString, itemLonFloat, centerLat, centerLon;
        items.forEach(function (mapItem) {
            counter = counter + 1;

            itemLatString = mapItem.Latitude;
            if (itemLatString === "") {
                counter = counter - 1;
            }
            else {
                itemLatFloat = itemLatString.replace(",", ".");
                itemLonString = mapItem.Longitude;
                itemLonFloat = itemLonString.replace(",", ".");
               
                sumOfLat = parseFloat(sumOfLat) + parseFloat(itemLatFloat);
                sumOfLon = parseFloat(sumOfLon) + parseFloat(itemLonFloat);
            }
            
        });
        centerLat = sumOfLat / counter;
        centerLon = sumOfLon / counter;

        map.setView({
            center: new Microsoft.Maps.Location(centerLat, centerLon),
            zoom: 13
        });
    }

    function displayInfobox(e) {
        pinInfobox.setOptions({ title: e.target.Title, description: e.target.Description, visible: true, offset: new Microsoft.Maps.Point(0, 25) });
        pinInfobox.setLocation(e.target.getLocation());
    }

    function hideInfobox(e) {
        pinInfobox.setOptions({ visible: false });
    }

    function addPushpins() {
        var test = '@Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Model).Replace("\\", string.Empty).Replace("\'",string.Empty))';
        //console.log(typeof (test));

        var items = JSON.parse(test);
        //console.log(items);

        items.forEach(function (mapItem) {
            addPushpinWithOptions(mapItem.Latitude, mapItem.Longitude, mapItem.Name);
        });
    };

    function addPushpinWithOptions(latitude, longitude, name) {
        latitude = latitude.replace(',', '.');
        longitude = longitude.replace(',', '.');
        var offset = new Microsoft.Maps.Point(0, 5);
        var pushpinOptions = {
            visible: true,
            textOffset: offset,
            draggable: false,
        };

        var pushpin = new Microsoft.Maps.Pushpin(
           new Microsoft.Maps.Location(latitude, longitude),
           pushpinOptions);

        pushpin.Title = name;
        pushpin.Description = "Latitude = " + latitude + "</br>" + "Longitude = " + longitude;

        pinLayer.push(pushpin); 
        Microsoft.Maps.Events.addHandler(pushpin, 'click', displayInfobox);

        var pushpinClick = Microsoft.Maps.Events.addHandler(pushpin, 'click', displayEventInfo);

        map.entities.push(pushpin);
        map.entities.push(pinLayer);
        map.entities.push(infoboxLayer);
    }

    displayEventInfo = function (e) {
        var obj = e.target;
        var info = "Events info - " + e.eventName + "\n";
        info += "Target  : " + obj.toString();
    }

</script>

<div id='myMap' style="position:relative; width:1140px; height:570px;"></div>

@using (Html.BeginForm("LoadedFromWiki","PlacedItem", FormMethod.Post))
{ 
    @Html.AntiForgeryToken()
    
<table class="table">
    <tr>
        <th>
            Dodać?
            @*@Html.DisplayNameFor(model => model.Add)*@
        </th>
        <th>
            Nazwa
            @*@Html.DisplayNameFor(model => model.Name)*@
        </th>
    </tr>

    @for (int i = 0; i < Model.Count; i++)
    {
        @Html.EditorFor(m => Model[i]);
        
        @*<tr>
            @Html.HiddenFor(modelItem => item.Name)
            @Html.HiddenFor(modelItem => item.Latitude)
            @Html.HiddenFor(modelItem => item.Longitude)
            @Html.HiddenFor(modelItem => item.Checked)
            @Html.HiddenFor(modelItem => item.ImageUrl)
            @Html.HiddenFor(modelItem => item.AddedDate)
            <td>
                @Html.EditorFor(modelItem => item.Add)
            </td>
            <td>
                @Html.EditorFor(modelItem => item.Name)
            </td>
        </tr>*@
    }
    </table>
    
    <input type="submit" value="Zapisz"/>
}

    <body onload="getMap();">
        <div id="MyMap">
        </div>
    </body>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

@*@(Html.Kendo().Grid<Eneo.Model.Models.ViewModels.PlacedItemModel>()
    .Name("PlacedMapItemsGrid")
    .Columns(cols =>
    {
        cols.Bound(p => p.PlacedItemID).Hidden();
        cols.Bound(p => p.Name);
        cols.Bound(p => p.Latitude);
        cols.Bound(p => p.Longitude);
        cols.Bound(p => p.Description);
        cols.Template(t => { }).HeaderTemplate("").ClientTemplate(
            @Html.ActionLink("Szczegóły", "Edit", new { id = "#=PlacedItemID#" }).ToHtmlString())
            .Width(105);
        cols.Command(cmd => { cmd.Destroy(); }).Width(105);
    })
    .DataSource(dataSource => dataSource
    .Ajax()
    .PageSize(20)
    .Model(model => model.Id(p => p.PlacedItemID))
            .Read(read => read.Action("PlacedMapItems_LoadFromWiki", "PlacedItem"))
                .Destroy(delete => delete.Action("PlacedMapItem_Delete", "PlacedItem"))
    )
    .Editable(editable => editable.Mode(GridEditMode.PopUp))
    .Scrollable(scrollable => scrollable.Height(430))
    .Sortable()
    .Filterable()
    .Scrollable()
    .Pageable(pageable => pageable
    .Refresh(true)
    .PageSizes(true)
    .ButtonCount(5))
)*@